# Generated by Django 5.1 on 2024-08-29 11:47

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("sub_title", models.CharField(blank=True, max_length=255, null=True)),
                ("about", wagtail.fields.RichTextField(blank=True, null=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("faq", 0)],
                        block_lookup={0: ("app_blocks.blocks.FAQListBlock", (), {})},
                    ),
                ),
                (
                    "hero_image_desktop",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image needs to be landscape 1920-w x 1200-h pixels.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "hero_image_mobile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image needs to be portrait 800-w x12000-h pixels.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
