# Generated by Django 5.1 on 2024-08-30 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("landing_funnels", "0002_alter_landingpage_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="landingpage",
            options={
                "verbose_name": "Landing Page Detail Page",
                "verbose_name_plural": "Landing Page Detail Pages",
            },
        ),
    ]
