# Generated by Django 5.1 on 2024-08-30 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_snippets", "0001_initial"),
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image needs to be portrait",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
    ]
