# Generated by Django 5.0.4 on 2024-04-18 16:24

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("images", "0001_initial"),
        ("wagtailcore", "0091_remove_revision_submitted_for_moderation"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffIndex",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "staff_hero",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "staff_hero_mobile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff",
                "verbose_name_plural": "Staff",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="StaffPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=255)),
                (
                    "job_catagory",
                    models.CharField(
                        choices=[
                            ("owner", "Owner / CEO"),
                            ("office", "Office Staff"),
                            ("sales", "Sales"),
                            ("project_manager", "Project Manager"),
                        ],
                        max_length=255,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "office_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "office_phone_ext",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "mobile_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("bio", wagtail.fields.RichTextField(blank=True)),
                (
                    "social_media_links",
                    wagtail.fields.StreamField(
                        [
                            (
                                "social_media_link",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "link_title",
                                            wagtail.blocks.CharBlock(
                                                label="External Link Title",
                                                max_length=100,
                                            ),
                                        ),
                                        (
                                            "link_block_external",
                                            wagtail.blocks.URLBlock(
                                                label="External Link URL. Use https://www.example.com",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
