# Generated by Django 5.0.4 on 2024-04-18 17:49

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_snippets", "0003_city"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffpage",
            name="counties",
            field=models.ManyToManyField(blank=True, to="admin_snippets.county"),
        ),
        migrations.AlterField(
            model_name="staffpage",
            name="social_media_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "social_media_link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "link_title",
                                    wagtail.blocks.CharBlock(
                                        label="External Link Title", max_length=100
                                    ),
                                ),
                                (
                                    "link_block_external",
                                    wagtail.blocks.URLBlock(
                                        label="External Link URL. Use https://www.example.com",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
