# Generated by Django 5.0.4 on 2024-04-18 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0002_staffpage_counties_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staffpage",
            old_name="image",
            new_name="headshot",
        ),
    ]
