# Generated by Django 5.0.4 on 2024-04-18 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
        ("staff", "0004_alter_staffpage_headshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffpage",
            name="headshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
    ]
