# Generated by Django 5.1 on 2024-08-29 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("location_funnels", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="locationindexpage",
            options={
                "verbose_name": "Location Index Page",
                "verbose_name_plural": "Location Index Pages",
            },
        ),
        migrations.AlterModelOptions(
            name="locationpage",
            options={
                "verbose_name": "Location Detail Page",
                "verbose_name_plural": "Location Detail Pages",
            },
        ),
        migrations.AlterModelOptions(
            name="locationpagearea",
            options={
                "verbose_name": "Location Area Page",
                "verbose_name_plural": "Location Area Pages",
            },
        ),
    ]
