# Generated by Django 5.1 on 2024-08-30 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogdetail",
            options={"verbose_name": "Blog Post", "verbose_name_plural": "Blog Posts"},
        ),
    ]
