# Generated by Django 5.1 on 2024-08-30 17:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("rich_text", 1), ("hero", 9)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "blockquote",
                            ]
                        },
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("content", 0)]], {}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Image needs to be landscape 1920-w x 1200-h pixels."
                        },
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Image needs to be portrait 800-w x 1200-h pixels."
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Optional", "required": False},
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {}),
                    7: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image_desktop", 2),
                                ("image_mobile", 3),
                                ("title", 4),
                                ("text", 5),
                                ("button", 6),
                                ("page_chooser", 7),
                            ]
                        ],
                        {},
                    ),
                    9: ("wagtail.blocks.StreamBlock", [[("hero", 8)]], {}),
                },
                null=True,
            ),
        ),
    ]
