# Generated by Django 5.1 on 2024-08-29 11:49

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("rich_text", 1),
                            ("h2", 2),
                            ("h3", 3),
                            ("faq", 4),
                            ("cta", 8),
                            ("quote", 9),
                            ("video", 11),
                            ("image_gallery", 15),
                            ("carousel", 21),
                            ("image_banner", 23),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "link",
                                        "blockquote",
                                    ]
                                },
                            ),
                            1: ("wagtail.blocks.StructBlock", [[("content", 0)]], {}),
                            2: ("app_blocks.blocks.H2Block", (), {}),
                            3: ("app_blocks.blocks.H3Block", (), {}),
                            4: ("app_blocks.blocks.FAQListBlock", (), {}),
                            5: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic"]},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Button text",
                                    "max_length": 100,
                                    "required": True,
                                },
                            ),
                            7: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 5), ("button", 6), ("page_chooser", 7)]],
                                {},
                            ),
                            9: ("app_blocks.blocks.QuoteBlock", (), {}),
                            10: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                            11: ("wagtail.blocks.StructBlock", [[("video", 10)]], {}),
                            12: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            13: ("wagtail.blocks.ListBlock", (12,), {}),
                            14: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 13), ("caption", 14)]],
                                {},
                            ),
                            16: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Image needs to be landscape 1920-w x 1200-h pixels."
                                },
                            ),
                            17: ("wagtail.blocks.CharBlock", (), {}),
                            18: ("wagtail.blocks.TextBlock", (), {}),
                            19: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image_desktop", 16),
                                        ("title", 17),
                                        ("text", 18),
                                        ("button", 17),
                                        ("page_chooser", 19),
                                    ]
                                ],
                                {},
                            ),
                            21: ("wagtail.blocks.StreamBlock", [[("slide", 20)]], {}),
                            22: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 22), ("caption", 14)]],
                                {},
                            ),
                        },
                        null=True,
                    ),
                ),
                (
                    "hero_image_desktop",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image needs to be landscape 1920-w x 1200-h pixels.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "hero_image_mobile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image needs to be portrait 800-w x12000-h pixels.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
