# Generated by Django 5.0.6 on 2024-05-28 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0003_category_hero_desktop_category_hero_mobile"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productsindex",
            name="category_hero_desktop",
        ),
        migrations.RemoveField(
            model_name="productsindex",
            name="category_hero_mobile",
        ),
        migrations.RemoveField(
            model_name="productsindex",
            name="page_ptr",
        ),
        migrations.AddField(
            model_name="productpage",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="categories.category",
            ),
        ),
        migrations.DeleteModel(
            name="ProductsCategoryPage",
        ),
        migrations.DeleteModel(
            name="ProductsIndex",
        ),
    ]
