# Generated by Django 5.0.6 on 2024-05-28 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
        ("products", "0003_productindexpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productindexpage",
            name="intro",
        ),
        migrations.AddField(
            model_name="productindexpage",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="productindexpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
    ]
