# Generated by Django 5.0.6 on 2024-05-28 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0004_delete_product"),
        ("products", "0004_remove_productindexpage_intro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpage",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="categories.subcategory",
            ),
        ),
    ]
