# Generated by Django 5.0.6 on 2024-05-28 18:21

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
        ("images", "0001_initial"),
        ("products", "0005_productpage_subcategory"),
        ("wagtailcore", "0093_uploadedfile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productpage",
            name="category",
        ),
        migrations.RemoveField(
            model_name="productpage",
            name="subcategory",
        ),
        migrations.CreateModel(
            name="ProductsCategoryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("menu_title", models.CharField(blank=True, max_length=100)),
                ("details", wagtail.fields.RichTextField(blank=True)),
                (
                    "category_brochure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documents.customdocument",
                    ),
                ),
                (
                    "subcategory_hero_desktop",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image needs to be landscape 1920-w x1080-h pixels.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "subcategory_hero_mobile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image needs to be portrait 800-w x1200-h pixels.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Category",
                "verbose_name_plural": "Products Categories",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ProductsIndex",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("description", wagtail.fields.RichTextField(blank=True)),
                (
                    "category_hero_desktop",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image needs to be 1920 pixels wide and 1200 pixels high.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "category_hero_mobile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image needs to be 800 pixels wide and 1200 pixels high.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Products",
                "verbose_name_plural": "Products",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.DeleteModel(
            name="ProductIndexPage",
        ),
    ]
